apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sample-go
  description: Same go
  annotations: 
    github.com/project-slug: matiasurrutia/sample-go
    backstage.io/source-ref: "https://github.com/matiasurrutia/sample-go"
    backstage.io/techdocs-ref: url:https://github.com/matiasurrutia/sample-go
    backstage.io/github-actions-id: https://github.com/matiasurrutia/sample-go
spec:
  type: service
  lifecycle: experimental
  owner: architecture
  providesApis:
    - sample-go-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: sample-go-api
  description: The Sample GO API
  tags:
    - sample-go
    - rest
  links:
    - url: https://github.com/swagger-api/swagger-petstore
      title: GitHub Repo
      icon: github
    - url: https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v3.0/petstore.yaml
      title: API Spec
      icon: code
spec:
  type: openapi
  lifecycle: experimental
  owner: architecture
  definition:
    $text: https://github.com/matiasurrutia/sample-go/blob/master/openapi.yaml
